CC = gcc
CPPFLAGS =
all: chapter01 chapter02

chapter01:  chapter01.c
	$(CC) $(CPPFLAGS) chapter01.c -o chapter01

chapter02:  chapter02.c
	$(CC) $(CPPFLAGS) chapter02.c -o chapter02


clean:
	rm chapter01
	rm chapter02
