CC = gcc
CPPFLAGS =
all: chapter01 chapter02 chapter03 chapter04

chapter01:  chapter01.c
	$(CC) $(CFLAGS) chapter01.c -o chapter01

chapter02:  chapter02.c
	$(CC) $(CFLAGS) chapter02.c -o chapter02

chapter03:  chapter03.c
	$(CC) $(CFLAGS) chapter03.c -o chapter03

chapter04:  chapter04.c
	$(CC) $(CPPFLAGS) chapter04.c -o chapter04

clean:
	rm chapter01
	rm chapter02
	rm chapter03
	rm chapter04
