CC = g++
CPPFLAGS = -Wall

chapter01:  chapter01.cpp
	$(CC) $(CPPFLAGS) chapter01.cpp -o chapter01

chapter06:  chapter06.cpp
	$(CC) $(CPPFLAGS) chapter06.cpp -o chapter06

chapter25:  chapter25.cpp
	$(CC) $(CPPFLAGS) chapter25.cpp -o chapter25

clean:
	rm chapter01 
	rm chapter06
	rm chapter25
